name: lgf
channels:
  - pytorch
  - conda-forge
dependencies:
  - python>=3.7
  - numpy
  - pytorch
  - torchvision
  - ignite
  - imageio
  - pandas
  - matplotlib
  - scikit-learn
  - tensorboardx
  - tqdm
  - pytest
  - pip
  - pip:
    - pyro-ppl>=1.0